"""Tests for single-commit Git destination export."""

from __future__ import annotations

from pathlib import Path

import shutil

import pytest

from copybarista.commands import CommandRunner
from copybarista.config import (
    FileSelection,
    FolderDestination,
    GitDestination,
    WorkflowConfig,
)
from copybarista.errors import ExportError
from copybarista.git import export_git, write_git_destination
from copybarista.workflow import WorkflowRunner


pytestmark = [
    pytest.mark.integration,
    pytest.mark.skipif(shutil.which("git") is None, reason="git not installed"),
]


def _config(remote: Path) -> WorkflowConfig:
    return WorkflowConfig(
        name="demo",
        mode="squash",
        source_root="project",
        files=FileSelection(include=("**",), exclude=()),
        transforms=(),
        folder=FolderDestination(),
        git=GitDestination(
            url=f"file://{remote.as_posix()}",
            branch="main",
            committer_name="Copybarista Test",
            committer_email="copybarista@example.com",
        ),
    )


def _source(tmp_path: Path) -> Path:
    source_ref = tmp_path / "repo"
    project = source_ref / "project"
    project.mkdir(parents=True)
    (project / "README.md").write_text("hello\n", encoding="utf-8")
    return source_ref


def test_export_git_creates_branch_and_manifest(tmp_path: Path):
    remote = tmp_path / "remote.git"
    remote.mkdir()
    config = _config(remote)

    manifest = export_git(config=config, source_ref=_source(tmp_path))

    assert [entry.destination for entry in manifest.files] == ["README.md"]
    assert _git(remote, "show", "main:README.md") == "hello\n"


def test_export_git_uses_copybarista_commit_message(tmp_path: Path):
    remote = tmp_path / "remote.git"
    remote.mkdir()
    config = _config(remote)

    export_git(config=config, source_ref=_source(tmp_path))

    assert (
        _git(remote, "log", "-1", "--format=%s", "main")
        == "Project import generated by Copybarista.\n"
    )


def test_write_git_destination_reports_noop_for_unchanged_tree(tmp_path: Path):
    remote = tmp_path / "remote.git"
    remote.mkdir()
    config = _config(remote)
    source_ref = _source(tmp_path)

    staged = WorkflowRunner(config=config, source_ref=source_ref).stage(
        tmp_path / "stage1"
    )
    first = write_git_destination(staged, destination=config.git)
    staged_again = WorkflowRunner(config=config, source_ref=source_ref).stage(
        tmp_path / "stage2"
    )
    second = write_git_destination(staged_again, destination=config.git)

    assert first.status == "updated"
    assert len(first.ref) == 40
    assert second.status == "noop"
    assert second.ref == config.git.url


def test_export_git_requires_destination_url(tmp_path: Path):
    config = _config(tmp_path / "remote.git")
    config = WorkflowConfig(
        name=config.name,
        mode=config.mode,
        source_root=config.source_root,
        files=config.files,
        transforms=config.transforms,
        folder=config.folder,
        git=GitDestination(),
    )

    with pytest.raises(ExportError, match="url"):
        export_git(config=config, source_ref=_source(tmp_path))


def test_export_git_does_not_initialize_invalid_existing_local_remote(
    tmp_path: Path,
):
    remote = tmp_path / "not-a-git-remote"
    remote.mkdir()
    (remote / "README.md").write_text("not a git repository\n", encoding="utf-8")
    config = _config(remote)

    with pytest.raises(ExportError, match="repository"):
        export_git(config=config, source_ref=_source(tmp_path))

    assert not (remote / "HEAD").exists()


def _git(remote: Path, *args: str) -> str:
    result = shutil.which("git")
    assert result is not None

    completed = CommandRunner().run(
        [result, "--git-dir", str(remote), *args],
    )
    return completed.stdout
